[workspace]
authors = ["boilcy <0x6c6379@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia", "cuda"]
name = "qarobo-pipecat"
platforms = ["win-64", "linux-aarch64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[target.unix.activation.env]
CUDA_HOME="$CONDA_PREFIX"
LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
[target.win-64.activation.env]
CUDA_HOME="%CONDA_PREFIX%"

[dependencies]
cuda-version="12.6.*"
loguru = ">=0.7.0,<0.8"
transformers = ">=4.56.1,<5"
numpy = ">=1.26.4,<2.3"
setuptools = ">=75.8.2,<81"
pip = ">=25.2,<26"

[pypi-dependencies]
misaki = { version = "*", extras = ["zh", "en"] }
# fix to 0.0.90, pipecat is under development, api may change
pipecat-ai = { version = ">=0.0.90, <0.0.91", extras = ["deepseek", "silero", "tracing", "deepgram", "openai", "cartesia", "whisper"] }
dotenv = ">=0.9.9, <0.10"
pyaudio = ">=0.2.14, <0.3"
faster-whisper = ">=1.1.1, <2"
kokoro = ">=0.9.4, <0.10"
omegaconf = ">=2.3, <3"
librosa = ">=0.11.0,<0.12"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.torch-cuda.dependencies]
pytorch-gpu = ">=2.5.1,<3"
torchaudio = ">=2.5.1,<3"

# --- Feature for Jetson Orin Nano (JP6) ---
[feature.torch-jetson-jp6]
platforms = ["linux-aarch64"]

[feature.torch-jetson-jp6.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }
torchvision = { version = ">=0.20.1", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }
torchaudio = { version = ">=2.5.1", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }
triton = { version = ">=3.4.0", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }

# --- Feature for Jetson Thor (SBSA) ---
[feature.torch-jetson-sbsa]
platforms = ["linux-aarch64"]

[feature.torch-jetson-sbsa.pypi-dependencies]
torch = { version = ">=2.9.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }
torchvision = { version = ">=0.24.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }
torchaudio = { version = ">=2.9.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }
triton = { version = ">=3.5.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }


[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://pypi.tuna.tsinghua.edu.cn/simple", "https://mirrors.aliyun.com/pypi/simple/", "https://mirrors.hust.edu.cn/pypi/web/simple"]
no-build-isolation = true

[environments]
desktop = { features = ["py310", "torch-cuda"], solve-group = "desktop" }
orin-nano = { features = ["py310", "torch-jetson-jp6"], solve-group = "jetson-jp6" }
thor = { features = ["py312", "torch-jetson-sbsa"], solve-group = "jetson-sbsa" }

[tasks.format]
cmd = "pixi exec --spec ruff ruff format ."

[tasks.bot]
cmd = "python bot.py -c config/local.yaml -v"
