[workspace]
authors = ["boilcy <0x6c6379@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia", "robostack-staging"]
name = "qarobo-pipecat"
platforms = ["win-64", "linux-aarch64"]
version = "0.1.0"

[target.unix.activation.env]
CUDA_HOME = "$CONDA_PREFIX"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
[target.win-64.activation.env]
CUDA_HOME = "%CONDA_PREFIX%"

[dependencies]
loguru = ">=0.7.0,<0.8"
transformers = ">=4.56.1,<5"
numpy = ">=1.26.4,<2.3"
setuptools = ">=75.8.2,<81"
pip = ">=25.2,<26"

[pypi-dependencies]
# fix to 0.0.90, pipecat is under development, api may change
pipecat-ai = { version = ">=0.0.90, <0.0.91", extras = [
    "deepseek",
    "silero",
    "tracing",
    "deepgram",
    "openai",
    "cartesia",
    "whisper",
] }
dotenv = ">=0.9.9, <0.10"
pyaudio = ">=0.2.14, <0.3"
faster-whisper = ">=1.1.1, <2"
omegaconf = ">=2.3, <3"
librosa = ">=0.11.0,<0.12"

[feature.py38.dependencies]
python = "3.8.*"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.cuda114.system-requirements]
cuda = "11.0"
[feature.cuda114.dependencies]
cuda-version = "11.4.*"

[feature.cuda126.system-requirements]
cuda = "12.0"
[feature.cuda126.dependencies]
cuda-version = "12.6.*"

[feature.cuda130.system-requirements]
cuda = "13.0"
[feature.cuda130.dependencies]
cuda-version = "13.0.*"

[feature.kokoro.pypi-dependencies]
misaki = { version = "*", extras = ["zh", "en"] }
kokoro = ">=0.9.4, <0.10"

[feature.torch-cuda.dependencies]
pytorch-gpu = ">=2.5.1,<3"

# --- Feature for G1 w/ Jetson Orin NX---
[feature.g1.dependencies]
# override the dependencies because orin nx is old
loguru = ">=0.7.0,<0.8"
transformers = ">=4.26.1,<5"
numpy = ">=1.10.4,<2.3"
setuptools = ">=63.4.3,<81"
pip = ">=22.3,<26"

[feature.g1.pypi-dependencies]
opencv-python = "*"
# unitree_sdk2py = { path = "./third_party/unitree_sdk2_python", editable = true }
# cyclonedds = { version = "==0.10.2" }

[feature.g1.pypi-options]
# no-binary = ["cyclonedds"]

# --- Feature for Jetson Orin NX (JP5) ---
[feature.torch-jetson-jp5]
platforms = ["linux-aarch64"]

[feature.torch-jetson-jp5.pypi-dependencies]
# https://developer.download.nvidia.com/compute/redist/jp/v$JP_VERSION/pytorch/$PYT_VERSION
torch = { url = "https://developer.download.nvidia.com/compute/redist/jp/v511/pytorch/torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl" }
#torchvision = { git = "https://github.com/pytorch/vision.git", tag = "v0.15.1" }
#torchaudio = { git = "https://github.com/pytorch/audio.git", tag = "v2.0.1" }

# --- Feature for Jetson Orin Nano (JP6) ---
[feature.torch-jetson-jp6]
platforms = ["linux-aarch64"]

[feature.torch-jetson-jp6.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }

# --- Feature for Jetson Thor (SBSA) ---
[feature.torch-jetson-sbsa]
platforms = ["linux-aarch64"]

[feature.torch-jetson-sbsa.pypi-dependencies]
torch = { version = ">=2.9.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = [
    "https://pypi.tuna.tsinghua.edu.cn/simple",
    "https://mirrors.aliyun.com/pypi/simple/",
    "https://mirrors.hust.edu.cn/pypi/web/simple",
]
no-build-isolation = true

[environments]
desktop = { features = [
    "py310",
    "cuda126",
    "torch-cuda",
    "kokoro",
], solve-group = "desktop" }
orin-nano = { features = [
    "py310",
    "cuda126",
    "torch-jetson-jp6",
    "kokoro",
], solve-group = "jetson-jp6" }
thor = { features = [
    "py312",
    "cuda130",
    "torch-jetson-sbsa",
    "kokoro",
], solve-group = "jetson-sbsa" }
g1 = { features = [
    "py38",
    "cuda114",
    "g1",
    "torch-jetson-jp5",
], solve-group = "jetson-jp5", no-default-feature = true }

[tasks.format]
cmd = "pixi exec --spec ruff ruff format ."

[tasks.bot]
cmd = "python bot.py -c config/local.yaml -v"
